-- liquibase formatted sql

-- changeset mehdi:1718470341845-1
-- preconditions onFail:MARK_RAN onError:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name='articles';
CREATE TABLE "articles" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 8) NOT NULL, "title" VARCHAR(255) NOT NULL, "author" VARCHAR(255) NOT NULL, "published" date NOT NULL, CONSTRAINT "articles_pkey" PRIMARY KEY ("id"));

-- changeset mehdi:1718470341845-2
-- preconditions onFail:MARK_RAN onError:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from information_schema.tables where table_name='comments';
CREATE TABLE "comments" ("id" INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 6) NOT NULL, "comment" TEXT NOT NULL, "article_id" INTEGER, CONSTRAINT "comments_pkey" PRIMARY KEY ("id"));
ALTER TABLE "comments" ADD CONSTRAINT "comments_article_id_fkey" FOREIGN KEY ("article_id") REFERENCES "articles" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION;


-- changeset mehdi:data
-- preconditions onFail:MARK_RAN onError:MARK_RAN
-- precondition-sql-check expectedResult:0 select count(*) from articles;
INSERT INTO "articles" values (1, 'test', 'mehdi', '2024-01-01');